#include "ip.h"
#include "icmp.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"
#include "log.h"
#include <stdlib.h>
#include <assert.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix
// The input address is in host byte order.
// Tips:
// rtable is a global variable defined in rtable.c
rt_entry_t *longest_prefix_match(u32 dst)
{
	log(INFO, "look for longest prefix for "IP_FMT, HOST_IP_FMT_STR(dst));
	rt_entry_t *pos, *entry = NULL;
	u8 len = 0;
	list_for_each_entry(pos, &rtable, list) {
		if((dst & pos->mask) == (pos->dest & pos->mask)) {
			if(pos->mask > len) {
				len = pos->mask;
				entry = pos;
			}
		}
	}
	return entry;
}

// different from function ip_forward_packet, ip_send_packet sends packet generated by router itself
// This function is used to send icmp packets.
// You can complete this function after completing icmp_send_packet, or directly integrate the function into icmp_send_packet.
// The interface to sendd the packet is specified by longest_prefix_match.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *in_ip = packet_to_ip_hdr(packet);
	rt_entry_t *rt = longest_prefix_match(ntohl(in_ip->daddr));
	if(rt == NULL){
		log(ERROR, "should have route to host: "IP_FMT, NET_IP_FMT_STR(in_ip->daddr));
		return;
	}
	iface_info_t *iface = rt->iface;
	in_ip->saddr = htonl(iface->ip);
	in_ip->checksum = ip_checksum(in_ip);
	if(rt->gw == 0)
		iface_send_packet_by_arp(iface, in_ip->daddr, packet, len);
	else
	 	iface_send_packet_by_arp(iface, htonl(rt->gw), packet, len);
}
